package cat.itb.m78.exercices.Trivial

class Question(
    val question: String,
    val answers: List<String>,
    val indexRightAnswe: Int = 0 //La resposta correcta sempre serà la primera
)

val Questions: List<Question> = listOf(
    Question("Quan va ser la hambruna russa de Tàrtara?",
        listOf("1921-1922", "1954-1955", "1919", "1905-1906")),
    Question("Quin és el país amb més habitants del món?",
        listOf("Xina", "Índia", "USA", "Brasil")),
    Question("Quin artista va pintar La Guernica?",
        listOf("Pablo Picasso", "Salvador Dalí", "Joan Miró", "Francisco de Goya")),
    Question("Quan va començar la Primera Guerra Mundial?",
        listOf("1914", "1920", "1905", "1899")),
    Question("Qui va ser l'autor de l'obra 'La Maja Desnuda'?",
        listOf("Francisco de Goya", "Diego Velázquez", "Pablo Picasso", "Salvador Dalí")),
    Question("Quina civilització va construir les piràmides d'Egipte?",
        listOf("Egípcia", "Maia", "Mesopotàmica", "Romana")),
    Question("Qui va ser el líder de la Revolució Francesa?",
        listOf("Maximilien Robespierre", "Napoleó Bonaparte", "Louis XVI", "Jean-Paul Marat")),
    Question("Quin esdeveniment històric va marcar el final de l'Imperi Romà d'Occident?",
        listOf("La caiguda de Roma el 476", "La caiguda de Constantinoble el 1453", "La batalla de Hastings el 1066", "La conquesta d'Alexandre el Gran")),
    Question("Quin moviment artístic va tenir una gran influència al segle XIX?",
        listOf("Impressionisme", "Barroc", "Renaixement", "Surrealisme")),
    Question("Qui va ser el pintor més destacat del Renaixement italià?",
        listOf("Leonardo da Vinci", "Caravaggio", "Giotto", "Tiziano")),
    Question("Quan va ser la caiguda de l'Imperi Bizantí?",
        listOf("1453", "1492", "1204", "1066")),
    Question("Quin artista va crear la 'Última Cena'?",
        listOf("Leonardo da Vinci", "Michelangelo", "Rafael", "Giotto")),
    Question("Quina ciutat va ser fundada com a Roma antiga?",
        listOf("Roma", "Atenes", "Carthago", "Alexandria")),
    Question("Qui va ser el déu principal de l'Olimp a la mitologia grega?",
        listOf("Zeus", "Hades", "Ares", "Apol·lo")),
    Question("Quina és la muntanya més alta del món?",
        listOf("Everest", "K2", "Makalu", "Kangchenjunga")),
    Question("Quin déu egipci era considerat el déu del sol?",
        listOf("Ra", "Osiris", "Horus", "Anubis")),
    Question("Quin religió té el budisme com a base?",
        listOf("Budisme", "Cristianisme", "Hinduisme", "Islam")),
    Question("On va néixer Buda?",
        listOf("Nepal", "Índia", "Tíbet", "Xina")),
    Question("Quina ciutat és considerada la 'ciutat santa' per al cristianisme, l'islam i el judaïsme?",
        listOf("Jerusalem", "La Meca", "Vaticà", "Medina")),
    Question("Quina és la capital de Japó?",
        listOf("Tòquio", "Kyoto", "Osaka", "Hokkaido")),
    Question("Quin va ser el país fundador de l'Imperi Inca?",
        listOf("Perú", "Bolívia", "Equador", "Colòmbia")),
    Question("Quin déu romà era equivalent a Zeus en la mitologia grega?",
        listOf("Júpiter", "Marte", "Neptú", "Apolo")),
    Question("Quina és la capital d'Índia?",
        listOf("Nova Delhi", "Bombai", "Calcutta", "Chennai")),
    Question("Qui va ser la mare de Zeus en la mitologia grega?",
        listOf("Rhea", "Gaia", "Hera", "Demèter")),
    Question("Quin déu grec era el déu del mar?",
        listOf("Posidó", "Apolo", "Ares", "Hermes")),
    Question("Qui era la deessa de la saviesa i la guerra a la mitologia grega?",
        listOf("Atena", "Artemis", "Hera", "Demèter")),
    Question("Quina criatura mitològica grega tenia cos de cavall i cap d'home?",
        listOf("Centaure", "Minotaure", "Sirena", "Hidra")),
    Question("Quin heroi grec va superar els dotze treballs?",
        listOf("Hèrcules", "Aquiles", "Ulisses", "Perseu")),
    Question("Quina és la capital de Tailàndia?",
        listOf("Bangkok", "Chiang Mai", "Phuket", "Pattaya")),
    Question("Quin és el nom tradicional del palau reial de Tailàndia?",
        listOf("Gran Palau", "Palau del Rei", "Palau Imperial", "Palau del Dèu")),
    Question("Com es diu la platja famosa de Tailàndia on es va rodar la pel·lícula 'La Playa'?",
        listOf("Maya Bay", "Phuket Beach", "Koh Phi Phi", "Railay Beach")),
    Question("Quin és l'animal símbol de Tailàndia?",
        listOf("Tigre", "Elefant", "Lleó", "Búfal")),
    Question("Quina religió és majoritària a Tailàndia?",
        listOf("Budisme", "Cristianisme", "Islam", "Hinduisme")),
    Question("Qui va desenvolupar la teoria de la relativitat?",
        listOf("Albert Einstein", "Isaac Newton", "Galileo Galilei", "Nikola Tesla")),
    Question("Quina és la fórmula de l'àrea d'un cercle?",
        listOf("πr²", "2πr", "πr", "r²")),
    Question("Quin esdeveniment va marcar el final de l'Imperi Romà d'Occident?",
        listOf("La caiguda de Roma el 476", "La batalla de Hastings el 1066", "La conquesta d'Alexandre el Gran", "La caiguda de Constantinoble el 1453")),
    Question("Qui va escriure 'Cien Anos de Soledad'?",
        listOf("Gabriel García Márquez", "Pablo Neruda", "Mario Vargas Llosa", "Jorge Luis Borges")),
    Question("Qui va ser l'autor de 'Don Quixot'?",
        listOf("Miguel de Cervantes", "Garcilaso de la Vega", "Luis de Góngora", "Francisco de Quevedo")),
    Question("Quina è la distància entre la Terra i el Sol?",
        listOf("149.6 milions de km", "100 milions de km", "200 milions de km", "50 milions de km")),
    Question("Quin filòsof grec va ensenyar a Plató?",
        listOf("Sòcrates", "Aristòtil", "Pitágoras", "Heràclit")),
    Question("Quin és el resultat de 3 elevat a la potència de 4?",
        listOf("81", "12", "27", "64")),
    Question("Quin esdeveniment va provocar l'inici de la Primera Guerra Mundial?",
        listOf("L'assassinat de l'Arxiduc Francesc Ferran", "L'atac a Pearl Harbor", "La caiguda de la muralla de Berlín", "La revolució russa de 1917")),
    Question("Qui va escriure 'Matar un rossinyol'?",
        listOf("Harper Lee", "Mark Twain", "Ernest Hemingway", "John Steinbeck")),
    Question("Quin filòsof grec va ser el mestre d'Alexandre el Gran?",
        listOf("Aristòtil", "Plató", "Sòcrates", "Epicur")),
    Question("Quina és la derivada de la funció f(x) = x²?",
        listOf("2x", "x²", "x", "2")),
    Question("Quina és la capital de l'Imperi Romà?",
        listOf("Roma", "Constantinoble", "Atenes", "Carthago")),
    Question("Qui va escriure '1984'?",
        listOf("George Orwell", "Aldous Huxley", "Ray Bradbury", "J.R.R. Tolkien")),
    Question("Quin esdeveniment va posar fi a l'Imperi Bizantí?",
        listOf("La caiguda de Constantinoble el 1453", "La caiguda de Roma el 476", "La batalla de Waterloo el 1815", "La conquesta de l'Índia")),
    Question("Quina és la fórmula de l'àrea d'un triangle?",
        listOf("1/2 * base * altura", "base * altura", "base + altura", "base²")),
    Question("Qui va escriure 'La Ilíada' i 'L'Odissea'?",
        listOf("Homer", "Sòfocles", "Eurípides", "Plató")),
    Question("Quina de les següents és una obra de William Shakespeare?",
        listOf("Hamlet", "Matar un rossinyol", "Don Quixot", "Cien años de soledad")),
    Question("Què va establir Isaac Newton amb les seves lleis del moviment?",
        listOf("La gravetat", "La relativitat", "La teoria quàntica", "Les lleis de l'electricitat")),
    Question("Quina és la fórmula de la suma d'una progressió aritmètica?",
        listOf("S = n/2 * (a1 + an)", "S = a1 * n", "S = a1 + n", "S = a1 * an")),
    Question("Qui va desenvolupar la teoria de l'evolució?",
        listOf("Charles Darwin", "Jean-Baptiste Lamarck", "Gregor Mendel", "Isaac Newton")),
    Question("Quina és la capital de França?",
        listOf("París", "Lió", "Marsella", "Bordeus")),
    Question("Quin esdeveniment va iniciar la Revolució Francesa?",
        listOf("La presa de la Bastilla", "La caiguda de l'Imperi Romà", "L'assassinat de l'Arxiduc Francesc Ferran", "La proclamació de la independència d'Amèrica")),
    Question("Quina és la fórmula de l'àrea d'un quadrat?",
        listOf("L²", "2L", "L * W", "L + W")),
    Question("Quin autor va escriure 'La metamorfosi'?",
        listOf("Franz Kafka", "Herman Melville", "James Joyce", "F. Scott Fitzgerald")),
    Question("Què és una integral en càlcul?",
        listOf("L'operació inversa de la derivada", "Una operació de multiplicació", "L'operació d'additionar números", "Una fórmula per a l'àrea d'un cercle")),
    Question("Quin filòsof va escriure 'La República'?",
        listOf("Plató", "Aristòtil", "Sòcrates", "Heràclit")),
    Question("Quin esdeveniment va causar la caiguda de l'Imperi Mongol?",
        listOf("La fragmentació de l'Imperi", "La conquesta dels Ming", "La invasió d'Alexandre el Gran", "La guerra dels Cent Anys")),
    Question("Quina és la capital de l'antic Egipte?",
        listOf("Tebes", "Alexandria", "Cairo", "Memphis")),
    Question("Què significa la paraula 'filosofia'?",
        listOf("Amor per la saviesa", "Estudi de la vida", "Estudi de la política", "Cerca de la veritat")),
    Question("Quin filòsof va proposar la teoria del contracte social?",
        listOf("Jean-Jacques Rousseau", "Immanuel Kant", "René Descartes", "Friedrich Nietzsche")),
    Question("Quina és la fórmula de la llei de Coulomb per a la força entre dues càrregues elèctriques?",
        listOf("F = k * (q1 * q2) / r²", "F = m * a", "F = k * q1 / r", "F = q * E")),
    Question("Qui va ser l'autor de 'El viatge al centre de la Terra'?",
        listOf("Jules Verne", "H.G. Wells", "Isaac Asimov", "Arthur C. Clarke")),
    Question("Quin esdeveniment va marcar el començament de l'era moderna?",
        listOf("La caiguda de Constantinoble el 1453", "La Revolució Industrial", "La proclamació de la independència d'Amèrica", "La caiguda de l'Imperi Romà"))
)