package cat.itb.m78.exercices.Trivial

class Question(
    val question: String,
    val answers: List<String>,
    val indexRightAnswe: Int = 0 //La resposta correcta sempre serà la primera
)

val QuestionsEasy: List<Question> = listOf(
    Question("Qui va ser el primer president dels Estats Units?",
        listOf("George Washington", "Abraham Lincoln", "Thomas Jefferson", "Benjamin Franklin")),
    Question("Quin eslògan va popularitzar el personatge de la pel·lícula *Forrest Gump*?",
        listOf("La vida és com una caixa de bombons", "El temps és or", "Un camí cap a la felicitat", "Mai no és massa tard")),
    Question("Quina va ser la gran civilització que va sorgir a l'antic Egipte?",
        listOf("Egípcia", "Romana", "Greca", "Mesopotàmica")),
    Question("Quin país té més habitants del món?",
        listOf("Xina", "Índia", "USA", "Brasil")),
    Question("Quin artista va pintar *La Joconda*?",
        listOf("Leonardo da Vinci", "Pablo Picasso", "Vincent van Gogh", "Salvador Dalí")),
    Question("Quin és l'últim planeta del sistema solar?",
        listOf("Neptú", "Urà", "Plutó", "Saturn")),
    Question("On va néixer la teoria de la relativitat?",
        listOf("Alemanya", "Estats Units", "França", "Suïssa")),
    Question("Quin animal és el més gran del planeta?",
        listOf("Balena blava", "Elefant", "Girafa", "Tigre")),
    Question("Quina guerra va començar l'any 1939?",
        listOf("Segona Guerra Mundial", "Primera Guerra Mundial", "Guerra Civil Espanyola", "Guerra de Corea")),
    Question("Quin va ser el primer home a trepitjar la lluna?",
        listOf("Neil Armstrong", "Buzz Aldrin", "Yuri Gagarin", "John Glenn")),
    Question("Quin és l'element químic amb el símbol 'O'?",
        listOf("Oxigen", "Ours", "Oli", "Odin")),
    Question("Quin invent va crear Alexander Graham Bell?",
        listOf("Telèfon", "Làmpada", "Cotxe", "Impressora")),
    Question("Quina és la capital de França?",
        listOf("París", "Roma", "Londres", "Madrid")),
    Question("Quin any va acabar la Segona Guerra Mundial?",
        listOf("1945", "1940", "1939", "1950")),
    Question("Quina llengua es parla a Brasil?",
        listOf("Portuguès", "Espanyol", "Francès", "Anglès")),
    Question("Quin és l'últim dia de la setmana?",
        listOf("Diumenge", "Dissabte", "Divendres", "Dijous")),
    Question("Quina famosa obra va escriure William Shakespeare?",
        listOf("Hamlet", "Don Quijote", "El Petit Príncep", "Cien años de soledad")),
    Question("Quin és l'instrument musical que té 88 tecles?",
        listOf("Piano", "Guitarra", "Violí", "Bateria")),
    Question("Quin era el nom del vaixell que va portar Cristòfor Colom a Amèrica?",
        listOf("Santa María", "Victoria", "Mayflower", "Endurance")),
    Question("Quina és la ciutat més gran del món per nombre d'habitants?",
        listOf("Tòquio", "Nova York", "Pequín", "Mumbai")),
    Question("Quina és la monarquia actual més antiga?",
        listOf("Regne Unit", "Japó", "Espanya", "Suècia")),
    Question("Quina és la moneda oficial del Japó?",
        listOf("Ien", "Dòlar", "Euro", "Yuan")),
    Question("Quina organització va guiar la creació de les Nacions Unides?",
        listOf("Organització de les Nacions Unides", "Lliga de Nacions", "OTAN", "FMI")),
    Question("Quina és la muntanya més alta del món?",
        listOf("Everest", "Kilimanjaro", "Aconcagua", "Mont Blanc")),
    Question("Quin element químic és essencial per a la respiració?",
        listOf("Oxigen", "Carboni", "Nitrogen", "Hidrogen")),
    Question("Quina guerra va tenir lloc entre 1914 i 1918?",
        listOf("Primera Guerra Mundial", "Segona Guerra Mundial", "Guerra de Corea", "Guerra de Vietnam")),
    Question("Quin va ser el primer animal a ser clonat?",
        listOf("Ovella Dolly", "Cavall", "Ratolí", "Gos")),
    Question("Quin és el continent més petit?",
        listOf("Oceania", "Europa", "Àfrica", "Amèrica")),
    Question("Quina ciutat és coneguda com la ciutat eterna?",
        listOf("Roma", "Atenes", "París", "Jerusalem")),
    Question("Quin és el nom de la primera civilització coneguda?",
        listOf("Mesopotàmica", "Egípcia", "Xinesa", "Indus")),
    Question("Quina és la pel·lícula d'animació de Disney amb una princesa anomenada Ariel?",
        listOf("La Sireneta", "Blancaneus", "Cenicienta", "La Bella i la Bèstia")),
    Question("Qui va compondre la famosa peça *Für Elise*?",
        listOf("Ludwig van Beethoven", "Johann Sebastian Bach", "Wolfgang Amadeus Mozart", "Frédéric Chopin")),
    Question("Quina època musical correspon a l'obra *La Traviata* de Verdi?",
        listOf("Romàntica", "Barroca", "Clàssica", "Renaixentista")),
    Question("Quin compositor va crear l'òpera *El barbero de Sevilla*?",
        listOf("Gioachino Rossini", "Giuseppe Verdi", "Richard Wagner", "Johann Strauss")),
    Question("Quina nota musical es troba entre Do i Re?",
        listOf("Do#", "Fa", "Mi", "Sol")),
    Question("Quin compositor va ser conegut com el *rei del vals*?",
        listOf("Johann Strauss II", "Wolfgang Amadeus Mozart", "Ludwig van Beethoven", "Frédéric Chopin")),
    Question("Quin és el resultat de 2 + 2?",
        listOf("4", "3", "5", "6")),
    Question("Quina és la forma geomètrica que té 4 costats iguals?",
        listOf("Quadrat", "Cercle", "Triàngul", "Rectangle")),
    Question("Quants costats té un hexàgon?",
        listOf("6", "5", "4", "8")),
    Question("Quants minuts té una hora?",
        listOf("60", "100", "24", "120")),
    Question("Quina és la suma de 10 i 15?",
        listOf("25", "20", "30", "35"))
)

val QuestionsMedium: List<Question> = listOf(
    Question("Quin filòsof va escriure *La República*?",
        listOf("Plató", "Aristòtil", "Sòcrates", "Epicur")),
    Question("Quin científic va descobrir la teoria de la relativitat?",
        listOf("Albert Einstein", "Isaac Newton", "Galileo Galilei", "Nikola Tesla")),
    Question("Quina guerra va tenir lloc entre 1914 i 1918?",
        listOf("Primera Guerra Mundial", "Segona Guerra Mundial", "Guerra Civil Espanyola", "Guerra de Corea")),
    Question("Quin és el nom del famós periodista que va cobrir la Guerra del Vietnam?",
        listOf("Walter Cronkite", "Edward R. Murrow", "Dan Rather", "Anderson Cooper")),
    Question("Qui va ser el creador de l'alfabet fenici?",
        listOf("Els fenicis", "Els grecs", "Els romans", "Els egipcis")),
    Question("Quina disciplina filosòfica va defensar René Descartes?",
        listOf("Racionalisme", "Empirisme", "Idealismo", "Pragmatismo")),
    Question("Quina és la teoria que va proposar Charles Darwin?",
        listOf("Evolució per selecció natural", "Teoria del Big Bang", "Teoria de la relativitat", "Teoria de la gravitació universal")),
    Question("En quin país va néixer Karl Marx?",
        listOf("Alemanya", "França", "Rússia", "Anglaterra")),
    Question("Quin era el nom del primer imperi romà?",
        listOf("Imperi Romà d'Occident", "Imperi Romà d'Orient", "Imperi Bizantí", "Imperi Romà")),
    Question("Quin va ser el primer emperador de la Xina?",
        listOf("Qin Shi Huang", "Wu Di", "Liu Bang", "Sun Quan")),
    Question("Quin és el nom del protagonista de *1984*, l'obra de George Orwell?",
        listOf("Winston Smith", "John Smith", "Orwell", "Wells")),
    Question("Quin va ser l'objectiu de la construcció de la muralla xinesa?",
        listOf("Defensar-se dels invasors", "Aïllar-se del món", "Conservar la cultura xinesa", "Protegir les rutes comercials")),
    Question("Qui va ser l'autor de la teoria de l'evolució?",
        listOf("Charles Darwin", "Gregory Mendel", "Alfred Russel Wallace", "Jean-Baptiste Lamarck")),
    Question("Quina obra va escriure Virgili?",
        listOf("Èneida", "Odisea", "Iliada", "Georgiques")),
    Question("Quin filòsof va proposar la teoria de les idees innates?",
        listOf("René Descartes", "John Locke", "Jean-Jacques Rousseau", "Immanuel Kant")),
    Question("Quin rei va manar construir el Palau de Versalles?",
        listOf("Lluís XIV", "Lluís XVI", "Francesc I", "Carles V")),
    Question("Qui va fundar l'imperi Mongol?",
        listOf("Genghis Khan", "Tamerlán", "Kubilaï Khan", "Kublai Khan")),
    Question("Quina ciutat va ser fundada per Ròmul i Rem?",
        listOf("Roma", "Atenes", "Cartago", "Esparta")),
    Question("Quin filòsof va ser el primer a defensar l'ús de la lògica com a eina de raonament?",
        listOf("Aristòtil", "Platón", "Sòcrates", "Epicur")),
    Question("Quina llengua va parlar Simón Bolívar?",
        listOf("Espanyol", "Francès", "Portuguès", "Anglès")),
    Question("Quina obra va escriure Homer?",
        listOf("Iliada", "Èneida", "Georgiques", "La divina comèdia")),
    Question("Quina teoria científica va proposar Isaac Newton?",
        listOf("Gravitació universal", "Relativitat general", "Teoria de la relativitat", "Evolució")),
    Question("En quina guerra va participar l'exèrcit rus a la dècada de 1850?",
        listOf("Guerra de Crimea", "Guerra Civil Americana", "Guerra Franco-Prussiana", "Primera Guerra Mundial")),
    Question("Quin gran esdeveniment es va produir el 1492?",
        listOf("Descobriment d'Amèrica", "Caiguda de Constantinoble", "Elena de Troia", "Fundació de Roma")),
    Question("Quin matemàtic va desenvolupar la teoria dels nombres primers?",
        listOf("Euclides", "Pitàgores", "Gauss", "Descartes")),
    Question("Qui va crear el primer alfabeto fonètic?",
        listOf("Els fenicis", "Els romans", "Els grecs", "Els egipcis")),
    Question("Quina obra de Beethoven va marcar el canvi cap al Romanticisme?",
        listOf("Simfonia nº 3, *Heroica*", "Simfonia nº 5", "Simfonia nº 9", "Simfonia nº 6")),
    Question("En quin segle es va començar a desenvolupar la música barroca?",
        listOf("Segle XVII", "Segle XVI", "Segle XVIII", "Segle XIX")),
    Question("Quin compositor és conegut per les seves innovacions en la música atonal?",
        listOf("Arnold Schoenberg", "Claude Debussy", "Johann Sebastian Bach", "Igor Stravinsky")),
    Question("Què és una clau en teoria musical?",
        listOf("Un símbol que indica la tonalitat d'una peça", "Una figura musical", "Un tipus de compàs", "Un interval de nota")),
    Question("Quina és la fórmula matemàtica per calcular el nombre de tons entre dues notes a l'escala cromàtica?",
        listOf("El logaritme base 2 de la relació de freqüències", "La diferència entre les freqüències", "Multiplicar la freqüència per 2", "Afegir 1 a la freqüència")),
    Question("Quina és la fórmula per calcular l'àrea d'un cercle?",
        listOf("π * r²", "2 * π * r", "π * d²", "r * h")),
    Question("Quina és la fórmula per calcular el perímetre d'un rectangle?",
        listOf("2 * (longitud + amplada)", "longitud * amplada", "longitud * 2", "amplada * 2")),
    Question("Quina és la fórmula per calcular la mitjana d'un conjunt de números?",
        listOf("La suma dels valors dividida pel nombre de valors", "El valor més gran menys el més petit", "La suma dels quadrats dels valors", "La multiplicació de tots els valors")),
    Question("Quina relació matemàtica descriu el teorema de Pitàgores?",
        listOf("a² + b² = c²", "a + b = c", "a - b = c", "a * b = c")),
    Question("Quants graus té un angle recte?",
        listOf("90", "180", "360", "45"))
)

val QuestionsHard: List<Question> = listOf(
    Question("Quin filòsof va proposar l'ètica de la virtut?",
        listOf("Aristòtil", "Platón", "Sòcrates", "Epicur")),
    Question("Quina va ser la causa de la caiguda de l'Imperi Romà?",
        listOf("Invasions bàrbares", "Crisi econòmica", "Corrupció interna", "Totes les anteriors")),
    Question("Quin autor va crear el concepte de *superhome*?",
        listOf("Friedrich Nietzsche", "Jean-Paul Sartre", "Karl Marx", "Martin Heidegger")),
    Question("Quin va ser el primer gran teòric del mètode científic modern?",
        listOf("Francis Bacon", "René Descartes", "Isaac Newton", "Albert Einstein")),
    Question("Quin filòsof va parlar de la *voluntat de poder*?",
        listOf("Friedrich Nietzsche", "Immanuel Kant", "Karl Marx", "Martin Heidegger")),
    Question("Quina va ser la filosofia defensada per Søren Kierkegaard?",
        listOf("Existencialisme", "Racionalisme", "Idealismo", "Pragmatismo")),
    Question("Qui va escriure *L'anticrist*?",
        listOf("Friedrich Nietzsche", "Jean-Paul Sartre", "Immanuel Kant", "Karl Marx")),
    Question("Quina va ser la civilització que va sorgir a l'antic Perú?",
        listOf("Inca", "Azteca", "Maia", "Olmeca")),
    Question("Quina és la teoria de la relativitat especial?",
        listOf("Albert Einstein", "Isaac Newton", "Galileo Galilei", "Niels Bohr")),
    Question("Quin autor va defensar el concepte de l'ésser com a 'voluntat'?",
        listOf("Arthur Schopenhauer", "Jean-Paul Sartre", "Friedrich Nietzsche", "Martin Heidegger")),
    Question("Quin era el nom de la guerra que va enfrontar França i Anglaterra entre 1337 i 1453?",
        listOf("Guerra dels Cent Anys", "Guerra de les Dues Roses", "Guerra Civil Anglesa", "Guerra de Napoleó")),
    Question("Quina va ser l'obra mestra de Michelangelo?",
        listOf("La Creació d'Adam", "L'Últim Judici", "David", "La Pietà")),
    Question("Quin és el nom del teòric de la *mà invisible*?",
        listOf("Adam Smith", "Karl Marx", "David Ricardo", "John Maynard Keynes")),
    Question("Quin esdeveniment va desencadenar la Revolució Francesa?",
        listOf("La crisi econòmica", "L'Assalt a la Bastilla", "La mort de Lluís XVI", "La gran por")),
    Question("Quin matemàtic va proposar els teoremes de les còniques?",
        listOf("Apollonius de Perge", "Euclides", "Arquímedes", "Pitàgores")),
    Question("Quin esdeveniment va ser l'inici de la Guerra Freda?",
        listOf("Conferència de Yalta", "Bloqueig de Berlín", "La caiguda de Berlín", "La creació de l'OTAN")),
    Question("Quin va ser el primer gran imperi de l'Antiga Mesopotàmia?",
        listOf("Sumeri", "Babilònic", "Assíria", "Persa")),
    Question("Qui va escriure *L'Espiritualitat de l'home*?",
        listOf("Jean-Paul Sartre", "Albert Camus", "Simone de Beauvoir", "Karl Marx")),
    Question("Quina obra de Johann Sebastian Bach està considerada una de les seves composicions més complexes per la seva polifonia?",
        listOf("*L'Art de la Fuga*", "*Matthäuspassion*", "*Conciertos de Brandeburgo*", "*Missa en si menor*")),
    Question("Quina innovació va aportar Claude Debussy a la música amb l'ús del *mode mixolidi*?",
        listOf("Va trencar amb les tonades tradicionals majors i menors", "Va introduir la dissonància harmònica", "Va crear noves estructures formals", "Va utilitzar estructures de 5/4")),
    Question("Quin és l'interval entre una nota *Do* i la seva octava superior?",
        listOf("8è", "7è", "6è", "5è")),
    Question("Quina relació matemàtica descriu la freqüència d'una nota i la seva octava superior?",
        listOf("La freqüència de l'octava superior és el doble de la freqüència original", "La freqüència és el doble del temps de durada", "La freqüència es divideix per 2 per cada octava", "No hi ha cap relació matemàtica entre elles")),
    Question("Quin matemàtic grec va establir la base de l'acústica i la teoria musical en analitzar les relacions entre intervals sonors?",
        listOf("Pitàgores", "Euclides", "Arquímedes", "Plató")),
    Question("Quina és la constant matemàtica que representa la relació entre la circumferència i el diàmetre d'un cercle?",
        listOf("π", "e", "i", "Φ")),
    Question("Quin és el nom de la fórmula que resol les equacions quadràtiques?",
        listOf("Fórmula general", "Fórmula de Cardano", "Fórmula de Newton", "Fórmula de l'arquimedes")),
    Question("Quina és la diferència entre un nombre primer i un nombre compost?",
        listOf("Un nombre primer només es pot dividir per ell mateix i 1", "Un nombre compost només té dos divisors", "Un nombre primer és divisble per 2", "Un nombre compost és menor que 10")),
    Question("Quin és el valor aproximat de la constant *e*, la base del logaritme natural?",
        listOf("2.718", "3.141", "1.618", "1.414")),
    Question("Quin matemàtic va introduir el concepte de números imaginaris?",
        listOf("René Descartes", "Carl Friedrich Gauss", "Leonhard Euler", "Joseph Fourier"))
)